#
# Copyright (C) 2018-2025 Ycarus (Yannick Chabanois) <ycarus@zugaina.org> for OpenMPTCProuter
#
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI WAN Metrics for OpenMPTCProuter
LUCI_DEPENDS:=+omr-metrics

PKG_LICENSE:=GPLv3

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
