#!/bin/sh /etc/rc.common
# Copyright (C) 2024 OpenWrt.org

START=99
STOP=10

USE_PROCD=1

PROG=/usr/sbin/bpftune
CONFIGFILE=/etc/config/bpftune

start_service() {
    local enabled logging_stdout tuners_disabled

    config_load bpftune
    config_get_bool enabled config 'enabled' '0'
    config_get_bool logging_stdout config 'logging_stdout' '0'
    config_get tuners_disabled config 'tuners_disabled' ''

    [ "$enabled" -eq 0 ] && {
	echo "bpftune is disabled in config"
	return 1
    }

    procd_open_instance
    procd_set_param command "$PROG"
    
    # Si logging vers stdout est activé
    [ "$logging_stdout" -eq 1 ] && {
	procd_append_param command -s
    }
    
    # Si des tuners doivent être désactivés
    [ -n "$tuners_disabled" ] && {
	for tuner in $tuners_disabled; do
	    procd_append_param command -d "$tuner"
	done
    }
    
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "bpftune"
}

reload_service() {
    stop
    start
}

status() {
    $PROG -S
}

query() {
    $PROG -q
}